### ISSUE TITLE
Account request notification shows email address

### ISSUE THREAD

**Issue by cmb69** [php/web-pecl#100]
When applying for a PECL account, the form at https://pecl.php.net/account-request.php has a checkbox labeled "Show email address?" This is certainly meant for privacy reasons, so the requesters email address won't be publicly shown if the checkbox isn't checked. Makes sense to me. However, the implementation is:

https://github.com/php/web-pecl/blob/ebc1d3af7111359347295edc3a37dfa1466fb9cf/public_html/account-request.php#L131-L132

Really?

Shouldn't that be something like the following instead:
````diff
 public_html/account-request.php | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/public_html/account-request.php b/public_html/account-request.php
index d938de05..0efff702 100644
--- a/public_html/account-request.php
+++ b/public_html/account-request.php
@@ -125,11 +125,11 @@ if (isset($_POST['submit'])) {
         ";
         $result = $database->run($sql, [$handle, $name, $email, $hash, $showemail ? 1 : 0, $homepage, $userinfo, gmdate('Y-m-d H:i')]);
 
+        $address = @$showemail ? $email : "(address hidden)";
         $msg = "Requested from:   {$_SERVER['REMOTE_ADDR']}\n".
                 "Username:         {$handle}\n".
                 "Real Name:        {$name}\n".
-                "Email:            {$email}".
-                (@$showemail ? " (show address)" : " (hide address)") . "\n".
+                "Email:            {$address}\n".
                 "Purpose:\n".
                 "$purpose\n\n".
                 'To handle: '.$container->get('scheme').'://'.$container->get('host')."/admin/?acreq={$handle}\n";
````

**Comment by jimwins** [comment]
I'm sure the flag is to indicate whether the email address should be shown on the PECL user page (like https://pecl.php.net/user/rasmus) and nobody was thinking about how the email would still be public because it's being sent to a publicly-archived mailing list.

I think your change is good.
