### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by jlopezcrd** [php/web-pecl#93]
Hi friends, I'm building a docker image with some resources from pecl web.

The build process fails when is getting a pecl package from the web

I've realized the SSL cert in the web is expired.

¿Could be the installation fails due to the invalid cert?

Regards

![image](https://github.com/php/web-pecl/assets/6699978/8d5cf759-d84d-427e-b30b-e445eeb6b805)
![image](https://github.com/php/web-pecl/assets/6699978/3ab14663-11a0-4197-8cb1-b60b572bf17e)

**Comment by GrahamCampbell** [comment]
Can confirm this.

<img width="1939" alt="image" src="https://github.com/php/web-pecl/assets/2829600/01aa156a-b9f6-490c-8446-7312fab324d1">

**Comment by k0d3r1s** [comment]
website can be opened using "Advanced" but there seems to be no way to use pecl if ssl connection fails. could do --ofline but it seems wrong to change all builds to offline pecl installs

**Comment by Girgias** [comment]
We are aware on this issue: https://news-web.php.net/php.internals/121040

**Comment by berkayturanci** [comment]
Here is our workaround for the temp fix;

`FROM php:7.4-fpm

# Set working directory
WORKDIR /var/www

# Add docker php ext repo
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

# Make the script executable
RUN chmod +x /usr/local/bin/install-php-extensions

# Install other PHP extensions
RUN install-php-extensions mbstring pdo_pgsql zip exif pcntl gd bcmath

# https://pecl.php.net/package/memcache
# https://github.com/php/php-src/issues/12174
# https://github.com/php/web-pecl/issues/93
# https://news-web.php.net/php.internals/121040
# Workaround to install memcached from its GitHub repo
RUN apt-get update && apt-get install -y git libmemcached-dev zlib1g-dev && \
    cd /tmp && \
    git clone https://github.com/php-memcached-dev/php-memcached.git memcache && \
    cd memcache && \
    phpize && \
    ./configure && \
    make && \
    make install && \
    docker-php-ext-enable memcached && \
    cd /var/www && \
    rm -rf /tmp/memcache`

**Comment by tony-karunairajan** [comment]
is there an ETA for this fix please?

**Comment by tonynilan** [comment]
Is there an ETA for the SSL renewal?

**Comment by exussum12** [comment]
Seems to be working now? Not seen an official update though

**Comment by jlopezcrd** [comment]
In my case, I'm getting "time out" response, or an slow loading..

**Comment by trittler** [comment]
Maybe the server is overwhelmed with simultaneous request?
... I got through now, and the certificate is now valid until December 10. 2023 🥳

**Comment by jlopezcrd** [comment]
> Maybe the server is overwhelmed with simultaneous request? ... I got through now, and the certificate is valid until December 10. 2023 🥳

Sure!

```
Package "pdo_sqlsrv" Version "5.11.1" does not have REST xml available
install failed
```

**Comment by Upperfoot** [comment]
Reminds me of this

![image](https://github.com/php/web-pecl/assets/2132945/2c1a97e9-5da7-466c-b81d-bdcb18bf653a)

**Comment by mlocati** [comment]
> @jlopezcrd same as you.
> `Package "igbinary" does not have REST info xml available`

It's there: see https://pecl.php.net/rest/r/igbinary/allreleases.xml

**Comment by Norris1z** [comment]
worked for me now
