### ISSUE TITLE
Handling of superseded packages is bad

### ISSUE THREAD

**Issue by cmb69** [php/web-pecl#98]
See for instance, https://pecl.php.net/package/pthreads; the text states "This package is not maintained anymore and has been superseded." Okay, but superseded by what? Looking at the [package info](https://pecl.php.net/package-edit.php?id=931) shows that for "superseded by" parallel has been chosen, but that is not stated in the user visible info.

Looking at the code:

https://github.com/php/web-pecl/blob/7de91eaabdb5437bc0ad6fea74b11fb845af599c/templates/pages/extension.php#L27-L48

So there is apparently no way to handle this case. Putting "parallel" in the "New Home Link (if moved out of PECL)" comes somewhat close ("This package is not maintained anymore and has been superseded. Package has moved to channel [parallel](https://pecl.php.net/package/parallel) package parallel"), but doesn't cut it.

I have no idea what `$superseded` is (no dev environment for web-pecl), but assuming it holds the package name, I think the first leg of the if statement should add a link to PECL/parallel, i.e.

````diff
 templates/pages/extension.php | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/templates/pages/extension.php b/templates/pages/extension.php
index 383dc355..0d6fc4e0 100644
--- a/templates/pages/extension.php
+++ b/templates/pages/extension.php
@@ -27,7 +27,8 @@
 <?php if ($superseded || $unmaintained): ?>
     <div class="warnings">
         <?php if ($superseded && $unmaintained): ?>
-            This package is not maintained anymore and has been superseded.
+            This package is not maintained anymore and has been superseded by
+            <a href="/package/<?= $this->noHtml($superseded) ?>"><?= $this->noHtml($superseded) ?></a>.
         <?php elseif ($superseded && !$unmaintained): ?>
             This package has been superseded, but is still maintained for bugs and security fixes.
         <?php elseif (!$superseded && $unmaintained): ?>
````

**Comment by mlocati** [comment]
> I have no idea what `$superseded` is

I looked for `/\bsuperseded\b/` across the whole project, and the only reference (except for `templates/pages/extension.php`) is here: https://github.com/php/web-pecl/blob/7de91eaabdb5437bc0ad6fea74b11fb845af599c/public_html/extension.php#L101

So, it seems that `$superseded` is a boolean.

**Comment by cmb69** [comment]
Thanks, @mlocati! I think we could use `$package['new_package']` then.

**Comment by cmb69** [comment]
I've opened #99, which might be easier to discuss.

> However, you snippet also has:
> 
> ```
>          <?php if ($package['new_channel'] === $host): ?> 
>              Use <a href="/package/<?= $this->noHtml($package['new_package']) ?>"> 
> ```
> 
> Which indicates this link should already be there?

`$package['new_channel']` is what I described:

> Putting "parallel" in the "New Home Link (if moved out of PECL)" comes somewhat close ("This package is not maintained anymore and has been superseded. Package has moved to channel [parallel](https://pecl.php.net/package/parallel) package parallel"), but doesn't cut it.

This is probably about alternative channels to PECL, which don't exist as far as I know.
